### ISSUE TITLE
Other user's voice chat is really quiet

### ISSUE THREAD

**Issue by srnyx** [plasmoapp/plasmo-voice#111] opened 2021-10-21 02:58 UTC
I turned up Voice Chat Volume to 200% and my game volume to 100%, the voices from other players are still pretty quiet, and sometimes hard to make out what they're saying.
I have to be within like 5 blocks of them to be able to hear what they're saying.

**Comment by Toldoven** [comment] 2021-10-21 20:35
Can you provide audio sample?

**Comment by srnyx** [comment] 2021-11-17 23:05
Sorry I took so long haha. Thought it fixed itself, turned out it didn't.
https://user-images.githubusercontent.com/25808801/142296623-62f96184-3cca-446b-b43c-77966f4d4d8c.mp4

**Comment by srnyx** [comment] 2021-11-26 01:05
@KPidS

**Comment by Toldoven** [comment] 2021-11-26 10:30
It's likely because you've set the threshold for a compressor and a limiter too low. Try turning it off, or just press "Reset" button to make it go back to the default value. https://imgur.com/aztdUve

**Comment by srnyx** [comment] 2021-11-26 16:00
> It's likely because you've set the threshold for a compressor and a limiter too low. Try turning it off, or just press "Reset" button to make it go back to the default value. [imgur.com/aztdUve](https://imgur.com/aztdUve)

~~Changing those don't make a difference for me.~~
Makes a small difference. But my own microphone (when testing) is also really quiet, even when turning Activation Threshold all the way down and Microphone Volume all the way up.

**Comment by Toldoven** [comment] 2022-01-28 18:53
Maybe it's the same issue as #151, should be fixed in the new version. If it's not, then I have no idea what can cause this. If the issue is still relevant and you are not on 1.18, wait for the 1.2.10 version of the mod to release, test it, and open a new issue if you still have this issue.

**Closed as completed by Toldoven** 2022-01-28 18:53 UTC
Labels: question
