### ISSUE TITLE
marked as ARR in curseforge and modrinth, but lgpl in github?

### ISSUE THREAD

**Issue by MenacingPerson** [plasmoapp/plasmo-voice#280] opened 2023-02-24 09:37 UTC
![image](https://user-images.githubusercontent.com/59611020/221144452-829432e4-d1b0-4cd5-9a00-81834e890d91.png)
![image](https://user-images.githubusercontent.com/59611020/221144514-49ee7a44-8c09-4b66-b07a-1a81768656c1.png)
![image](https://user-images.githubusercontent.com/59611020/221144601-1a8f25a1-e248-4a81-bc08-06890fadf959.png)

**Comment by thehaffk** [comment] 2023-03-24 07:27
We appreciate your concern regarding the discrepancies in copyright information about our product across different platforms. 

We would like to clarify that the authoritative copyright for our product is indeed under the GNU Lesser General Public License v3.0 (LGPL-3.0), as stated on our GitHub repository. We apologize for any confusion caused by inconsistencies on CurseForge and Modrinth.

Our team is committed to maintaining accurate and consistent information across all platforms, and we assure you that we will rectify this issue. Following the release of Plasmo Voice 2.0.0, we plan to update the copyright information on both CurseForge and Modrinth to correctly reflect the LGPL-3.0 license.

Thank you for bringing this matter to our attention, and we hope this clears up any misunderstandings. Should you have any further questions or concerns, please do not hesitate to reach out to us.

Our Discord https://discord.gg/qgFdm7rB7H

**Comment by Toldoven** [comment] 2023-03-31 09:27
Plasmo Voice 1xx is ARR, Plasmo Voice 2xx is LGPL

**Closed as completed by Toldoven** 2023-03-31 09:27 UTC
